Fix glibc compatibility of Docker image
Native libraries such as snappy which we use for compression are linked against glibc, but the Alpine-based Docker image only has musl. This caused exceptions such as the following:

```
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.10-8ed119fb-cf4b-4d95-a845-e352e3c5d243-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.10-8ed119fb-cf4b-4d95-a845-e352e3c5d243-libsnappyjava.so)
```

The gcompat package solves this by providing a glibc compatibility layer on top of musl.

Signed-off-by: nscuro <nscuro@protonmail.com>