Fix flaky RoleResourceTest
Occasionally, `RoleResourceTest` would fail in CI with the following exception(s):

```
javax.jdo.JDOUserException: Object with id "" is managed by a different persistence manager
	at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:701)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:702)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:722)
	at alpine.persistence.AbstractAlpineQueryManager.lambda$persist$1(AbstractAlpineQueryManager.java:316)
	at alpine.persistence.Transaction.call(Transaction.java:139)
	at alpine.persistence.AbstractAlpineQueryManager.callInTransaction(AbstractAlpineQueryManager.java:542)
	at alpine.persistence.AbstractAlpineQueryManager.callInTransaction(AbstractAlpineQueryManager.java:553)
	at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:316)
	at org.dependencytrack.persistence.RoleQueryManager.createRole(RoleQueryManager.java:60)
	at org.dependencytrack.persistence.QueryManager.createRole(QueryManager.java:815)
	at org.dependencytrack.persistence.DefaultObjectGenerator.loadDefaultRoles(DefaultObjectGenerator.java:350)
	at org.dependencytrack.persistence.DefaultObjectGenerator.loadDefaultRoles(DefaultObjectGenerator.java:335)
	at org.dependencytrack.resources.v1.RoleResourceTest.before(RoleResourceTest.java:62)
```

This happens because `DefaultObjectGenerator` populates a static map with persistent objects. Due to the map being static, it's shared across all tests.

Signed-off-by: nscuro <nscuro@protonmail.com>