Fix HikariCP failure to create meter registry
Since upgrading to HikariCP v6.3.1, setting the meter registry no longer works:

```
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.zaxxer.hikari.metrics.micrometer.MicrometerMetricsTrackerFactory.<init>(io.micrometer.prometheusmetrics.PrometheusMeterRegistry)
	at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:123)
	at com.zaxxer.hikari.pool.HikariPool.setMetricRegistry(HikariPool.java:292)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:103)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
	at alpine.server.persistence.PersistenceManagerFactory.createTxPooledDataSource(PersistenceManagerFactory.java:308)
```

Switching to `setMetricsTrackerFactory` resolves the issue. Seems like a reflection bug in HikariCP.

Signed-off-by: nscuro <nscuro@protonmail.com>